---
- name: create django project
  shell: "django-admin startproject {{project_name}}"
  args:
    chdir: "{{user_home}}"
    creates: "{{project_dir}}"
  become: yes
  become_user: "{{user}}"

# Run syncdb on the application
- name: django migrate
  django_manage:
    command: migrate
    app_path: "{{ project_dir }}"
    virtualenv: "{{user_home}}/newproject/newenv"



